### ISSUE TITLE
ImportError: cannot import name NestedXBlockSpec

### ISSUE THREAD

**Issue by tkeemon** [open-craft/problem-builder#96]
I don't have a whole lot of time to look into this error at the moment, but I wanted to create this Issue before I forgot.

It seems like there was some sort of conflict between enabled XBlocks for a particular course. We had the following in the Advanced Module List:
```
[
    "library_content",
    "step-builder",
    "problem-builder",
    "table",
    "pdf",
    "edx_sga",
    "poll",
    "survey"
]
```

After trying to create a new Unit, I was redirected to Studio's 500 error page. 

From /edx/var/log/supervisor/lms-stderr.log:
```
2016-02-02 15:05:20,951 ERROR 18990 [root] exceptions.py:9 - Uncaught exception from <class 'django.core.handlers.wsgi.WSGIHandler'>
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/component.py", line 169, in container_handler
    component_templates = get_component_templates(course)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/component.py", line 335, in get_component_templates
    component_display_name = xblock_type_display_name(category, default_display_name=category)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/helpers.py", line 157, in xblock_type_display_name
    component_class = XBlock.load_class(category, select=settings.XBLOCK_SELECT_FUNCTION)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/plugin.py", line 118, in load_class
    PLUGIN_CACHE[key] = cls._load_class_entry_point(selected_entry_point)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/edx/app/edxapp/xblocks/problem-builder/problem_builder/mentoring.py", line 41, in <module>
    from .step_review import ReviewStepBlock
  File "/edx/app/edxapp/xblocks/problem-builder/problem_builder/step_review.py", line 27, in <module>
    from xblockutils.studio_editable import (
ImportError: cannot import name NestedXBlockSpec
2016-02-02 15:05:20,952 ERROR 18990 [django.request] base.py:213 - Internal Server Error: /container/block-v1:Appsembler+Demo1001+Fall2015+type@vertical+block@0e5700cd5bb742b6a7e90a6c6e587bb6
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/component.py", line 169, in container_handler
    component_templates = get_component_templates(course)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/component.py", line 335, in get_component_templates
    component_display_name = xblock_type_display_name(category, default_display_name=category)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/helpers.py", line 157, in xblock_type_display_name
    component_class = XBlock.load_class(category, select=settings.XBLOCK_SELECT_FUNCTION)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/plugin.py", line 118, in load_class
    PLUGIN_CACHE[key] = cls._load_class_entry_point(selected_entry_point)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/edx/app/edxapp/xblocks/problem-builder/problem_builder/mentoring.py", line 41, in <module>
    from .step_review import ReviewStepBlock
  File "/edx/app/edxapp/xblocks/problem-builder/problem_builder/step_review.py", line 27, in <module>
    from xblockutils.studio_editable import (
ImportError: cannot import name NestedXBlockSpec
```

My workaround for this error was to remove `problem-builder` from the Advanced Module List. I've never encountered a conflict like this with XBlocks. 

If it makes any difference, we're currently running a forked version of named-release/cypress.

Do you guys have any ideas?

**Comment by bradenmacdonald** [comment]
The version of [xblock-utils](https://github.com/edx/xblock-utils/) that comes with Cypress is too old to be compatible with newer versions of problem builder. You should be able to fix the issue by upgrading to the latest version of xblock-utils, or the version specified in Problem Builder's [requirements.txt file](https://github.com/open-craft/problem-builder/blob/86f86e24/requirements.txt#L4).

**Comment by tkeemon** [comment]
That seems to have done it. Thanks for your help @bradenmacdonald.
